root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["local_generate"]
  bin = "/usr/bin/make"
  cmd = "/usr/bin/true"
  delay = 1000
  exclude_dir = ["public", "tmp"]
  exclude_file = ["out.css"]
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "theme", "content"]
  include_ext = ["go", "md", "templ", "css", "js", "yaml"]
  include_file = ["templum.go", "page.go"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
