version: "2"
run:
  tests: false
linters:
  disable:
    - contextcheck
    - depguard
    - err113
    - errchkjson
    - exhaustruct
    - goconst
    - ireturn
    - lll
    - mnd
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - theme
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cugu/templum)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
