run:
  timeout: 5m
  tests: false
linters:
  # enable-all: true
  disable:
    - contextcheck
    - depguard
    - err113
    - errchkjson
    - execinquery
    - exhaustruct
    - goconst
    - gomnd
    - ireturn
    - lll
    - mnd
    - varnamelen
    - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cugu/templum)
issues:
  exclude-dirs:
    - theme