run:
  go: "1.22"
  timeout: 5m
  tests: false
linters:
  enable-all: true
  disable:
    - depguard
    - errchkjson
    - exhaustruct
    - goconst
    - err113
    - mnd
    - gomnd
    - ireturn
    - lll
    - varnamelen
    - wrapcheck
    - execinquery
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cugu/templum)
