// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package plain

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"bytes"
	"context"
	"io"
	"strings"

	"github.com/a-h/templ"

	"github.com/cugu/templum"
)

func link(c *pageContext, config map[string]string, page *templum.Page, depth int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}

		ctx = templ.InitializeContext(ctx)

		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}

		ctx = templ.ClearChildren(ctx)

		var templ_7745c5c3_Var2 = []any{
			"block",
			"p-2",
			"rounded",
			"w-full",
			templ.SafeClass("hover:bg-gray-700"),
			templ.KV("font-bold", strings.HasPrefix(c.Active, page.Slug())),
			templ.KV("font-normal", !strings.HasPrefix(c.Active, page.Slug())),
			templ.KV("bg-gray-700", c.Active == page.Slug()),
		}

		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(page.Slug()))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		var templ_7745c5c3_Var3 templ.SafeURL = templ.URL(config["base_url"] + page.Href())

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var2).String()))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		var templ_7745c5c3_Var4 string = page.Title()

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}

		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}

		return templ_7745c5c3_Err
	})
}
