name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod }

      - name: Lint
        run: |
          make install_golangci_lint
          make lint

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod }

      - name: Fmt
        run: |
          make install-dev
          make install_golangci_lint
          make fmt

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod }

      - name: Test
        run: make test
